# --- Basic options --- #

# Name of website
title: "Sarvesh Aadhithya's Portfolio"

# Short description of your site
description: "CTF Writeups and Cybersecurity Blogs"

# Your name to show in the footer
author: "Sarvesh Aadhithya"

# --- Navigation Links --- #
navbar-links:
  Writeups: "/writeups"
  Blogs: "/blogs"

# --- Logo --- #
# Path to avatar image in the navbar
avatar: "/assets/img/3jd.png"    # Add your profile picture here
round-avatar: true               # Make the avatar circular

# --- Footer --- #
# Social network links
social-network-links:
  email: "apr4h.ctf@gmail.com"  # Your contact email
  twitter: "_Apr4h"             # Your Twitter handle
  rss: false                     # Remove RSS feed

# --- General Options --- #
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

# Website URL
url-pretty: "https://zoozoo-sec.github.io"

# --- Colors / Background --- #
navbar-col: "#68686b"             # Navbar background color
navbar-text-col: "#ffffff"        # Navbar text color
navbar-border-col: "#2d3142"      # Navbar border color
page-col: "#ffffff"               # Page background color
link-col: "#0077b6"               # Link color
hover-col: "#1d3557"              # Link hover color
footer-col: "#68686b"             # Footer background color
footer-text-col: "#ffffff"        # Footer text color
footer-link-col: "#2a9d8f"        # Footer link color

# --- SEO and Analytics --- #
# Google Analytics (optional)
#google_analytics: ""

# --- Comments --- #
# Uncomment and configure if you want to add comments in the future
#disqus: "your-disqus-shortname"

# --- Date and Pagination --- #
title-separator: "-"
date_format: "%B %-d, %Y"
timezone: "Asia/Kolkata"

# --- Markdown and Syntax Highlighting --- #
markdown: kramdown
highlighter: rouge

# Permalinks for blog posts
permalink: /:year-:month-:day-:title/
paginate: 5

# --- Jekyll Plugins --- #
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# --- Default values --- #
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
      readtime: true
  - scope:
      path: "" 
    values:
      layout: "page"
      show-avatar: true

# --- Exclude these files from production site --- #
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
